functionality:
  name: combine_columns
  namespace: demo
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      multiple: true
      required: true
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      required: true
      direction: output
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: nextflow
    variant: vdsl3
    directives:
      container: rocker/r-ver:4.1