functionality:
  name: remove_comments
  namespace: demo
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      example: "file.tsv"
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      required: true
      direction: output
      example: "file.tsv"
  resources:
  - type: bash_script
    path: script.sh
platforms:
  - type: nextflow
    variant: vdsl3
    directives:
      container: ubuntu:20.04
